<#
.SYNOPSIS
    
    This is the index of all the scripts inside the /terminal directory
    That connects the dots between all the scripts, its syntax and related manuals and know-how-stuffs

.DESCRIPTION
    
    This PowerShell script acts as an entry point to access the vast collections of
    -> Scripts {bat,py,ps1,vbs)
    -> Manuals {how specific syntax,script operates or what arguments to on which scripts}
    ->  . 
    
.PARAMETER

    

.EXAMPLE
    
    
     
.AUTHOR
    
    -Sanjeev Stephan Murmu

.LINK

.NOTES
    

.
-------------------------------|| CODE_BELOW ||-----------------------------#>
$message="Terminal Index"
./show-figlet.ps1 "$message"
#figlet "Main Index"
Write-Output "Execution Begins from here"
Write-Output "Main Entry gate for the terminal scripts,manual,syntax,shortcuts and so on"
<# 
-------------------------------|| CODE_ABOVE ||-----------------------------
------------------------------|| TERMINAL LOG ||----------------------------

PS D:\terminal>


-------------------------------|| HOW THE SCRIPT WORK ||--------------------




#>
